### PR TITLE
committing test2 in branchX

### PR DESCRIPTION
**Pull request by SKgithub2**
Hi,
This is SKgithub2 -from Mac  Writting to Uno-Shri of Window , 
I have created Test2 and commited to branchX . Please Review and approve.
Regards,
SKgithub2

### CODE REVIEW

**Comment by Uno-Shri** [comment]
Hi Skgithub2
Your codelooks good to me Uno-Shri
Please add on emore testcase into it
Regards,
Uno-Shri

**Comment by SKgithub2** [comment]
Hi , made changes second commit in branch X to approve

**Comment by Uno-Shri** [comment]
Hi SKgithub2,
Your code looks good, go ahead with merge to master

**Comment by SKgithub2** [comment]
take off..Final Merging now...

**Review by Uno-Shri — APPROVED** [review]

**Comment by SKgithub2** [comment]
Take off 2 --mearging

**Pull request merged**
